import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToasterProvider } from "@/components/ToasterProvider";
import { Providers } from "@/redux/store/providers/StoreProvider";
import AppInitializer from "@/components/AppInitializer";
// import Nav from "@/components/layout/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RPR DUET Admission Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Providers>
          <AppInitializer>
            <ToasterProvider />
            {/* <Nav></Nav> */}
            <main>{children}</main>
            {/* <Footer></Footer> */}
          </AppInitializer>
        </Providers>
      </body>
    </html>
  );
}
